### PR TITLE
Some simple refactoring done here.

### PR DESCRIPTION
**Pull request by feldrim**
1. The one giant auto-generated file is now gone, leaving 1300+ classes with their own files.
2. Fixes some simple formatting.

Still needs work to do:
* **The classes with "1"  in their names:** They are all inheriting CodeType and include nothing at all. There are classes with almost the same name -without 1 in the name- inheriting these. E.g.: `public partial class BatchStatus1Type : CodeType` and `public partial class BatchStatusType : BatchStatus1Type`. I couldn't have a closer look at the schemas but I'm pretty sure these could and should be deleted.

* **Partial:** Why these classes are all partial? I wanted to remove it but I thought maybe some of them -among 1300+ classes- need to be partial. So I left them for now.

### CODE REVIEW

**Comment by feldrim** [comment]
I'll make another request, so closing this.

**Comment by jpdillingham** [comment]
Thanks for the PR!  My thoughts:

Personally I only see a downside to refactoring this code; the XML conversion will need to be repeated for any update to the source XML schema and the refactoring will need to be repeated as well.  Version 0700 is in the works, so this will be a reality in a soonish timeframe.

If refactoring is really necessary I feel that it should be done by an automated tool rather than manually (or with ReSharper or some other extension) so that it is repeatable and less error prone.  I would be willing to contribute to such a tool if we can collaborate on a list of refactorings.

Lastly I noticed you are targeting C# 7.0 features with 4.6.2; this has broken the CI builds.  I think 4.6.1 is fine for now but if any refactoring is to be done .NET Standard 2.0 should be targeted.  This will require a new project, and it may be an opportunity to move the repo to MESA's org (@JoeDo?)



Adding @BrentHumphreys because I know he started similar work.

**Comment by feldrim** [comment]
Thank you for the quick feedback. It has been fun and yes, I agree with you on using automated methods. And thanks for the warning on .Net configuration.

**Comment by BrentHumphreys** [comment]
Funny... I have done much of the same, and considered a PR for it.  I did use an automated tool to split the files (ReSharper), but wasn't terribly impressed with the results.

From a class perspective, my instinct was to split these classes up into the various namespaces.

The XML committee is indeed gearing up to implement the upcoming ISA 95 model changes, and hopefully incorporate some things that make B2MML more friendly to use in other serialization formats like JSON.  We will see how that works out.... the quote I like from json.org is that XML is a good document exchange format, while JSON is a good data exchange format.    My current thinking is that we adopt that sentiment within the B2MML project so that we can limit the scope of what we attempt to represent in JSON.  So in essence, a lot of the transaction elements in B2MML would remain strictly XML, but we could develop JSON-schema (http://json-schema.org/specification.html) for many of the B2MML data types.

Sorry, went way past the scope of this PR, but eager to get the dialog started.

**Comment by feldrim** [comment]
It's been enlightening for me to be in a discussion with you. At first I thought it would be a better idea to auto-generate the code by myself using a t4 template. Well, it wasn't quite easy. Then I choose xsd2code but the result were not satisfactory too. So I used some help from ReSharper and decided to make a contribution, bot the best but just one tiny step further for the sake of clean code.msdn.microsoft.com have a few points to share.

First, I agree with @BrentHumphreys 's idea of organizing through namespaces.The schemas provide different context for business, which could be counted as an equivalent for namespaces in OOP languages.

Second, the result never seemed like an OOP code. As far as I see -It's a bit time consuming to review 1300+ classes- there is almost no business logic in them and I belive there shouldn't be any also. They keep state, not behavior so DTO seems be the possible result of generation, not a Poco. Yet, DTOs are classes to help transferring data, B2MML schemas include the representation of the structure of business domain. This makes me to think about generating POCOs through XSD but then use DTOs manually crafted for business needs.

Third, connected with the OOP thoughts above, where should the abstract classes and interfaces fit in the result core base? If I decide to create these classes manually, how should I start? Of course I'd try to create my design by writing interfaces first. So auto-generated code should create and implement interfaces, but how? I agree with @jpdillingham 's statement that the refactoring doesn't need to be done by hand but must be done automatically. The thing is automatically generated code is just code written by another code, which reflects the developer's mind and skill set. I believe manual refactorings like this -but not this, this is just simple cleanup- will help us to reconsider what the output should be like. In that case, I believe, it's possible to create a healthier code generator. So these efforts seem like educational experiences for the future.

Forth an the last, finally, T4 templates are a better way to get healthier results because they are more customizable and practical. Starting to code a T4 template and evolving it into a better OOP code generator until the next version of B2MML comes would be an interesting challenge.

**Comment by BrentHumphreys** [comment]
I like the T4 idea, but I am not terribly experienced in that area.    We might want to consider a template engine that allows us to define templates to target multiple output formats (while t4 should be ok for that, I don't know that a Java developer working in eclipse on unix will be able to generate using T4).

The ISA 95 team is now using Enterprise Architect (Sparx systems) to manage the 95 model.  I am a big fan of EA, and the tooling available for design and generation,

One thing I am exploring for the XML committee is to see if we can work with the 95 EA Model as a starting point for B2MML.  In an ideal world, we could then generate C#/Java/etc. all directly from the model, with the outputs, simply being the same output just in a different language or schema.

I could see a case for creating a separate repository under the MESA International account to manage the tooling around B2MML and using the schema in a variety of languages/formats.

**Pull request closed without merging**
